### ISSUE TITLE
Change wifi !

### ISSUE THREAD

**Issue by ConradoP** [maccoylton/esp-homekit-sonoff-mini#1]
Good afternoon, I used OTA firmaware to install your code.

It worked perfectly, congratulations !!!

But I can not reset it, how can I do? I need to change the wifi network!
Without flashing again is it possible?

**Comment by ConradoP** [comment]
I tested holding the button for a long time, it blinked as it had reset.
But it doesn't work, it goes back to the HOME app to be added

**Comment by maccoylton** [comment]
>I tested holding the button for a long time, it blinked as it had reset. ...

@ConradoP I must have commented out the Wi-Fi reset code, travelling this week, I will release an update version next week 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ConradoP** [comment]
Thank you!!!!!!!!

**Comment by maccoylton** [comment]
Sorry it took so long, implement now, press the button for reset button on the mini for 5 seconds and it will go into access point mode, should server out as SonoffMini-XXXX. Once you have the latest firmware there is also a new characteristic, accessible in Eve, that works the same as OTA, set it to on and the device will reboot into the same access point mode.
