### ISSUE TITLE
compatibility with firmware 3.6 new DIY approach

### ISSUE THREAD

**Issue by haroldl82** [maccoylton/esp-homekit-sonoff-mini#12]
Hi,

I have been trying all over Weekend to flash my Sonoff mini using the new 3.6 approach (OTA) but I can't make it work.
curl http://192.168.1.181:8081/zeroconf/ota_flash -X POST
-d ‘{“deviceid”: “1000dc9cc8” , “data”: {“downloadUrl”: “http://192.168.1.71:8000/main.bin“, “sha256sum”: “d12c8fb96b4cce4d570124488ebf874922fb2c2412d1001f37f01b9e1b580435”}}’

do you know if your firmware is still working with the new firmware 3.6?

many thanks

**Comment by maccoylton** [comment]
We have not previously been able to get out bootloader and firmware onto a Sonoff device using Sonoff DIY mode.  Only ever succeeded with a physical connection to flash per the Wiki

**Comment by ialidigital** [comment]
Probably worth putting this in the Wiki explicitly - I just toasted two mini's before reading this!

**Comment by maccoylton** [comment]
You should be able to recover them through a physical connection. I'll add a note to the wiki

**Comment by ialidigital** [comment]
@maccoylton good call - some rudimentary soldering and seem to have come back to life - somewhat!

Different issue now, but I'll post separately.
