### ISSUE TITLE
OTA update issue

### ISSUE THREAD

**Issue by xd94402002** [maccoylton/esp-homekit-sonoff-mini#14]
After join in the network
the device led blink for a while and nothing happened. 
no device appear in home app

**Comment by ialidigital** [comment]
Assuming you have successfully flashed the boot loader? 

If so, what stage did you get to?

From the wiki:
1) select your WiFi by clicking on it
2) enter your WiFi password
3) enter the GitHub directory - maccoylton/esp-homekit-sonoff-mini
4) enter filename - main.bin.
5) LED GPIO should be set to 13
6) click the join button

then:
7) Open Apple Home App and add accessory 
8) choose button 'I don't have a code or cannot scan'
9) select Sonoff Switch 
10) choose 'Add Anyway' option > use pairing code 111-111-11

Let us know and we can try and help?

FYI I flashed five of these a few days ago and all worked fine.

Can you also supply:

Version of Sonoff Mini firmware before flashing boot loader (difference in protocols)
What version board is the Sonoff-Mini
Which device are you using the Apple Home App on
What OS and tooling did you use to flash the boot loader

Happy New Year!

:)

**Comment by xd94402002** [comment]
Problem solved. 
Not sure what happen during the OTA update.
After stage2 step 6 "click the join button" the device led start blinking and I wait for a long time but nothing happen. 
I flash the newest otaboot.bin  (LCM version) from HomeACcessoryKid.
Then everything went great just like the wiki instructions. 
Thanks for reply. 

P.S.
Sonoff mini version 1.2

Happy New Year!

**Comment by maccoylton** [comment]
When you click the join button it can take some time before the accessory is ready to pair. 

The device reboots and the bootloader checks it has the the latest version of itself installed, it the checks it has the latest version of OTA install, then finally downloads and install the actual Sonoff  Mini firmware, you can track all this by issue the command 'nc -kulnw0 45678' in a terminal window.
