### ISSUE TITLE
new OTA?

### ISSUE THREAD

**Issue by haroldl82** [maccoylton/esp-homekit-sonoff-mini#16]
_"NOTE DUE SOME CHANGES ON GITHUB IN ORDER TO CONTINUE TO BE ABLE TO RECEVIE OTA UDATES PLEASE PERFORM A FIRMARE UPDATE BY CHOSING THE FIRMARE UPDATE OPTION IN THE EVE APP. THIS WILL UPDATE THE BOOTLOADER AND OTA PORTION OF THE FIRMARE TO ENSURE CONTINUED ACCESS TO OTA CAPABILITIES. THIS NEEDS TO BE DONE BY END OF MARCH 2021."_

Hey,
Are you saying we need to use a new boatload.bin version and re flash all son off mini?

thx

**Comment by maccoylton** [comment]
All you need to do is trigger a firmware upgrade using the Eve app.

**Comment by haroldl82** [comment]
Hey,
I am trying to flash a sonoff mini r2 however after having completed stage 2, the light constantly flashes blue (it was working very well before). I guess the issue is related to the Github change of end of march 2021. Am I supposed to use a newer version of bootload.bin?
( I have almost all my home switches on sonoff<->HomeKit, great stuff!).
many thanks

**Comment by maccoylton** [comment]
I update the release with the latest bootloader. Try flashing that

**Comment by haroldl82** [comment]
thanks for the answer.
Have you posted the new bootloader? The latest commit seems to be from 27 Jan 2020. Or have you posted elsewhere?

many thanks

**Comment by maccoylton** [comment]
I updated the latest release with the new bootloader.bin file. Download that and flash over a serial connection.

**Comment by haroldl82** [comment]
it works! many thanks

**Comment by maccoylton** [comment]
Great .. thanks for letting me know
