### ISSUE TITLE
Last state power

### ISSUE THREAD

**Issue by cristidobrescu** [maccoylton/esp-homekit-sonoff-mini#17]
Really love this trick on R2 mini. It is posible to enable Last State Power on this flash? I mean if the light is on and the power fall off, when it came back the R2 mini stay off, it is not returning to it last state power, on

**Comment by maccoylton** [comment]
Yes that is possible, might take a little while to add as I'm working on some other projects at the moment

**Comment by cristidobrescu** [comment]
Ok, got it, let me know about it. Thanks

**Comment by maccoylton** [comment]
had some time earlier and created a prototype, try installing the latest pre-release. A new option will show up in the Eve app , to allow you to preserve state over a power outage. Let me know how it goes

**Comment by cristidobrescu** [comment]
Thanks

**Comment by maccoylton** [comment]
Implemented and released
