### ISSUE TITLE
Sonoff DUAL R3

### ISSUE THREAD

**Issue by alexandrerochasalles** [maccoylton/esp-homekit-sonoff-mini#18]
Any chance for that to work with sonoff DUAL R3 (dual relay)?

**Comment by maccoylton** [comment]
Would possible, unfortunately I don't have a device to prototype on

**Comment by alexandrerochasalles** [comment]
That's such a pity, would be amazing to have this HomeKit controller in a tiny dual relay.

Anyway, cheers for your amazing job here!! 
Thank you for sharing this with us.

**Comment by maccoylton** [comment]
If you want to  sponsor the purchase of a device, I would be happy to do a firmware version for it. Just be aware as the Dual R3 ss a different chipset the it would not have the OTA functionality.
