### ISSUE TITLE
error to build

### ISSUE THREAD

**Issue by toshibochan** [maccoylton/esp-homekit-sonoff-mini#2]
please help I'm getting error

make -C examples/esp-homekit-sonoff-mini/src flash
make: Entering directory '/home/user/projects/esp-homekit-demo/examples/esp-homekit-sonoff-mini/src'
CC /home/user/projects/esp-homekit-demo/examples/esp-homekit-sonoff-mini/components/esp-homekit/src/server.c
/home/user/projects/esp-homekit-demo/examples/esp-homekit-sonoff-mini/components/esp-homekit/src/server.c:25:19: fatal error: cJSON.h: No such file or directory
 #include <cJSON.h>
                   ^
compilation terminated.
/home/user/projects/esp-homekit-demo/examples/esp-homekit-sonoff-mini/components/esp-homekit/component.mk:37: recipe for target 'build/homekit//src/server.o' failed
make: *** [build/homekit//src/server.o] Error 1
make: Leaving directory '/home/user/projects/esp-homekit-demo/examples/esp-homekit-sonoff-mini/src'

**Comment by toshibochan** [comment]
I change some things and now this:

make -C examples/esp-homekit-sonoff-mini/src flash
make: Entering directory '/home/user/projects/esp-homekit-demo/examples/esp-homekit-sonoff-mini/src'
CC /home/user/projects/esp-homekit-demo/examples/esp-homekit-sonoff-mini/src/main.c
AR build/program.a
LD build/main.out
./build/homekit.a(server.o): In function `homekit_server_on_get_characteristics':
/home/user/projects/esp-homekit-demo/examples/esp-homekit-sonoff-mini/components/esp-homekit/src/server.c:3162: undefined reference to `cJSON_Parse'
/home/user/projects/esp-homekit-demo/examples/esp-homekit-sonoff-mini/components/esp-homekit/src/server.c:3162: undefined reference to `cJSON_GetObjectItem'
/home/user/projects/esp-homekit-demo/examples/esp-homekit-sonoff-mini/components/esp-homekit/src/server.c:3162: undefined reference to `cJSON_Delete'
/home/user/projects/esp-homekit-demo/examples/esp-homekit-sonoff-mini/components/esp-homekit/src/server.c:3162: undefined reference to `cJSON_GetArraySize'
/home/user/projects/esp-homekit-demo/examples/esp-homekit-sonoff-mini/components/esp-homekit/src/server.c:3162: undefined reference to `cJSON_GetArrayItem'
/home/user/projects/esp-homekit-demo/examples/esp-homekit-sonoff-mini/components/esp-homekit/src/server.c:3162: undefined reference to `cJSON_Print'
/home/user/projects/esp-homekit-demo/examples/esp-homekit-sonoff-mini/components/esp-homekit/src/server.c:3162: undefined reference to `cJSON_Parse'
/home/user/projects/esp-homekit-demo/examples/esp-homekit-sonoff-mini/components/esp-homekit/src/server.c:3162: undefined reference to `cJSON_GetObjectItem'
./build/homekit.a(server.o):(.text.homekit_server_on_update_characteristics+0x15f): undefined reference to `cJSON_Delete'
./build/homekit.a(server.o):(.text.homekit_server_on_update_characteristics+0x17a): undefined reference to `cJSON_GetArraySize'
./build/homekit.a(server.o):(.text.homekit_server_on_update_characteristics+0x19e): undefined reference to `cJSON_GetArrayItem'
./build/homekit.a(server.o):(.text.homekit_server_on_update_characteristics+0x1a6): undefined reference to `cJSON_Print'
./build/homekit.a(server.o):(.text.homekit_server_on_update_characteristics+0x1cb): undefined reference to `cJSON_GetObjectItem'
./build/homekit.a(server.o):(.text.homekit_server_on_update_characteristics+0x202): undefined reference to `cJSON_GetObjectItem'
./build/homekit.a(server.o):(.text.homekit_server_on_update_characteristics+0x26e): undefined reference to `cJSON_GetObjectItem'
./build/homekit.a(server.o): In function `process_characteristics_update':
/home/user/projects/esp-homekit-demo/examples/esp-homekit-sonoff-mini/components/esp-homekit/src/server.c:3162: undefined reference to `cJSON_GetObjectItem'
/home/user/projects/esp-homekit-demo/examples/esp-homekit-sonoff-mini/components/esp-homekit/src/server.c:3162: undefined reference to `cJSON_GetArraySize'
/home/user/projects/esp-homekit-demo/examples/esp-homekit-sonoff-mini/components/esp-homekit/src/server.c:3162: undefined reference to `cJSON_GetArrayItem'
/home/user/projects/esp-homekit-demo/examples/esp-homekit-sonoff-mini/components/esp-homekit/src/server.c:3162: undefined reference to `cJSON_GetObjectItem'
/home/user/projects/esp-homekit-demo/examples/esp-homekit-sonoff-mini/components/esp-homekit/src/server.c:3162: undefined reference to `cJSON_GetObjectItem'
/home/user/projects/esp-homekit-demo/examples/esp-homekit-sonoff-mini/components/esp-homekit/src/server.c:3162: undefined reference to `cJSON_GetArraySize'
/home/user/projects/esp-homekit-demo/examples/esp-homekit-sonoff-mini/components/esp-homekit/src/server.c:3162: undefined reference to `cJSON_Delete'
./build/shared_functions.a(shared_functions.o):(.text.checkWifiTask+0x4): undefined reference to `wifi_check_interval'
./build/shared_functions.a(shared_functions.o):(.text.on_homekit_event+0x34): undefined reference to `accessory_init_not_paired'
./build/shared_functions.a(shared_functions.o): In function `on_homekit_event':
/home/user/projects/esp-homekit-demo/examples/esp-homekit-sonoff-mini/components/esp-homekit-common-functions/shared_functions/shared_functions.c:178: undefined reference to `accessory_init_not_paired'
collect2: error: ld returned 1 exit status
/home/user/projects/esp-open-rtos/common.mk:232: recipe for target 'build/main.out' failed
make: *** [build/main.out] Error 1
make: Leaving directory '/home/user/projects/esp-homekit-demo/examples/esp-homekit-sonoff-mini/src'

**Comment by maccoylton** [comment]
BTW you do know you  can  just flash you device with a pre-compiled binary .. right?

If you really want to build your own version, then I suspect your build environment is not set up correctly. Can she show me the directory structure under /home/user/projects/esp-homekit-demo/examples/

**Comment by maccoylton** [comment]
A realised I hadn't written the Wiki for this accessory,. now added

**Comment by toshibochan** [comment]
Thank you I will take look when I back home!

**Comment by toshibochan** [comment]
How long the installation takes before I can add to home app?

**Comment by toshibochan** [comment]
yay I was able to install thank you very much.
but have one error in your wiki.
say erase_flash but have to be write_flash

esptool.py -p /dev/cu.usbserial erase_flash esptool.py -p /dev/cu.usbserial --baud 230400 write_flash -fs 8m -fm dout -ff 40m 0x2000 otaboot.bin 0x0 rboot.bin 0x1000 blank_config.bin

esptool.py -p /dev/cu.usbserial write_flash esptool.py -p /dev/cu.usbserial --baud 230400 write_flash -fs 8m -fm dout -ff 40m 0x2000 otaboot.bin 0x0 rboot.bin 0x1000 blank_config.bin

**Comment by maccoylton** [comment]
Thanks Wiki updated.
