### ISSUE TITLE
occasional shutdowns

### ISSUE THREAD

**Issue by Rastafabisch** [maccoylton/esp-homekit-sonoff-mini#20]
I’m experiencing occasionally shutdowns that I cannot reproduce nor determine any underlying patterns. I flashed an Sonoff Mini some years ago, which is running fine ever since (apart from some rare lost wifi issues). Now a few weeks pack I flashed another one. While basically working as it should, it sometimes shuts down power. Occasionally it happens every other minute, while sometimes it works fine for hours.
The issue is especially bothering as the Mini is meant to control my parents TV, Apple TV and receiver.

Might it be related to power draw?

Sadly I cannot re-flash as a measure to troubleshoot the issue as I ripped a solder pad (TX) after flashing last time. 
If someone could point me to some documentation to find another spot to solder to, I would try this first. 

Btw.: both Minis run on the latest 0.2.4 firmware. However they are deployed in different homes and thus Wi-Fi networks.

**Comment by maccoylton** [comment]
The chances are this is related to Wi-Fi stability causing the device to restart. Can you provide any logs? You can use  udplog-client running on another machine on the same network to capture the log.

**Comment by maccoylton** [comment]
closing as no further feedback
