### ISSUE TITLE
On/Off cycle repeatedly whilst having Wifi, but no Internet connection

### ISSUE THREAD

**Issue by ialidigital** [maccoylton/esp-homekit-sonoff-mini#21]
Had a fibre outage recently for an entire day. All of my mini's, which are connected to lights, if the light was turned on, would every cycle (from light on state) off 5 secs, then back on, pretty much every minute (maybe two mins) or so.

Throughout the whole period my local wifi was solid.

This happened until the fibre connection was restored.

Is this designed behaviour?

**Comment by maccoylton** [comment]
This shouldn't happen, sounds like the mini's are restarting, which suggests some kind of network issue causing. What version of IOS are you running and what device is your home hub, what version is the Homehub running? Also have you upgrade to the new homekit architecture?

**Comment by maccoylton** [comment]
closed as no further info provided
