### ISSUE TITLE
After flash sonoff mini cycling reboot 

### ISSUE THREAD

**Issue by rserra** [maccoylton/esp-homekit-sonoff-mini#3]
Hello,

After flashing sonoff mini with the your binary the mini reboots constantly. The same with binary after compiling.

Regards,
Rodrigo

**Comment by maccoylton** [comment]
How did you flash?  Did you follow the instructions in the WiKi? Need more details, I have a number of these running at home, and other users have reported success

**Comment by rserra** [comment]
I use "make flash" command

**Comment by maccoylton** [comment]
Please follow the instructions on the Wiki, as this firmware uses the OTA mechanism, make flash will not work, unless you have already  installed and run a pre-built firmware
