### ISSUE TITLE
Flash with Sonoff DIY Tool?

### ISSUE THREAD

**Issue by erkatron** [maccoylton/esp-homekit-sonoff-mini#4]
Can I install this firmware with Sonoff DIY Tool? If so, can you describe the steps?

**Comment by maccoylton** [comment]
I have not yet found a way to do that. Sonoff Mini uses a different boot loader which appears to be causing issues. I am still looking at this and will let you know if I have success.

**Comment by erkatron** [comment]
Thanks for your answer @maccoylton . Do you know if there some other way to flash the Mini Over The Air?

**Comment by maccoylton** [comment]
Not to my knowledge, sorry

**Comment by Midifreakz** [comment]
Hey @maccoylton. How would I be able to flash this firmware on to the sonoff mini? I have it connected with a USB controller. soldered on the connectors. Can you give me a hint on where to start?

**Comment by toshibochan** [comment]
I was able to do doing this.
https://github.com/maccoylton/esp-homekit-sonoff-mini/wiki

**Comment by Midifreakz** [comment]
Great! I just discovered this by going trough the older issues. I have successfully flashed the firmware on to the Sonoff Mini but after selecting the SSID, wifi Password, and other file info I do not get the accessory to appear inside homekit... What should I try?
