### ISSUE TITLE
Can't add device to Homekit

### ISSUE THREAD

**Issue by Midifreakz** [maccoylton/esp-homekit-sonoff-mini#5]
Okay so by now I was able to get the accessory to show up in Homekit as Sonoff-Mini-13139836
I need to enter the 8 digit code to pair the device with homekit. I've tried 13139836 but without any luck. What am I missing here?

Also tried:

11111111
00000000
12345678

**Comment by Midifreakz** [comment]
UPDATE: After leaving the device overnight it paired with code 11111111

**Comment by maccoylton** [comment]
Yes, that the code. Recetly I;ve seen some issue with pairing. Just rety after a few minutes and it wi work

**Comment by ialidigital** [comment]
Could you add the pairing code explicitly to the Wiki as well :) sorry to be a PITA, avoid noobs asking later  - UX ++

**Comment by maccoylton** [comment]
done
