### ISSUE TITLE
Firmware update question 

### ISSUE THREAD

**Issue by toshibochan** [maccoylton/esp-homekit-sonoff-mini#6]
Hi @maccoylton i see on EVE app have option to do firmware update. If do firmware update will have to setup the device all over again?

**Comment by toshibochan** [comment]
What is debug task stats?

**Comment by maccoylton** [comment]
Firmware update pulls the latest code and reboot the accessory, no need for any setup. 

Task stats is for my debug/optimisation purposes, it tells we what size of stack each task requires, I can then fine tune to optimise memory usage

**Comment by toshibochan** [comment]
Great! Update work perfect! Thanks!!!!!
