### ISSUE TITLE
Connection 

### ISSUE THREAD

**Issue by Swabeats** [maccoylton/esp-homekit-sonoff-mini#7]
Hi,
I use my old (basically new :p) switches at home. My sonoff know that they have to make connection with the WiFi (access points or modem) as close as possible. Still I have some kind of a delay. Sometimes it works flawless, the other day it’s not 100% trustable. What can be the problem? PS wifey getting pissed :p. 
![BC4AB208-C28B-4327-B687-9E77E8E1075F](https://user-images.githubusercontent.com/60329961/73143400-bd666600-4099-11ea-83b4-f2cf88979e5a.png)
![F79168A2-246D-4C36-9172-056D97F44B93](https://user-images.githubusercontent.com/60329961/73143401-bd666600-4099-11ea-9c45-4eb180b0ad4b.png)
![2F5EF8D5-27FE-4E6A-9113-BDE5842F814F](https://user-images.githubusercontent.com/60329961/73143409-cfe09f80-4099-11ea-88c5-4dbd2f0c6e8a.jpeg)
![Uploading 647B3CEF-A919-40E4-8BFD-6CAEDD9CB603.jpeg…]()
![Uploading 8DB6FCFF-D6DE-4985-BEC2-96CD94D8D2F6.jpeg…]()
![Uploading C3009101-72FE-4BB1-ADD1-2099B5915AF9.jpeg…]()

**Comment by maccoylton** [comment]
Sounds like wifi connection issues. Is this the only SonoffMini you have? Can you  please run a continuous ping in the terminal and see  if there is packet loss. Can you also run the command  in another terminal window and let it run .. "dns-sd -B _hap._tcp."

**Comment by Swabeats** [comment]
Hey maccoylton. Thank you for the fast reply.

I ran the command in an other window. I have no wifi issues. No package loss.
I still did notice some delay on couple of Sonoff. I have 9 of them (planning to add 4 more).

I changed it with another Sonoff and - for now - it's ok and responding. 
I even changed the old switch to check but problem is due the sonoff. 

<img width="997" alt="Screenshot 2020-01-27 at 17 24 10" src="https://user-images.githubusercontent.com/60329961/73201233-da05ab00-4138-11ea-8954-974744012609.png">

**Comment by maccoylton** [comment]
Ok, I would recommend you leave both commands running and see what the output is when you are actually seeing an issue with the switch. If I understand you correctly you have 8 working ok, and 1 that has had issues l, so that very squarely points to either a hardware issue with that one or its connectivity because if it’s position. Monitoring the ping and the dns-sd while problems are occurring willl give us more info. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Swabeats** [comment]
I've 3 'bad' ones. So I had one Sonoff left from Amazon and replaced it to test. 
I'll do a check-up with the misses how our dressing lights work this week. If ok, I'll buy more Sonoff and replace the bad ones. 

Can the Sonoff who are not 100% reliable be fixed in ant kind of way?

Thanks in advance. Great guy!

**Comment by maccoylton** [comment]
I 'd be surprised if this was a hardware issue on so many devices. I've only had one sonoff device fail over the last couple of years. When you are having the issue, does the switch still work, is it just that it show not responding in the home app?  

Please provide feedback on the dns-sd command and the ping command at the time when the issue is happening. 

Can you also compile and run the udplog client https://github.com/HomeACcessoryKid/UDPlogger this will give us trace from the device, again leave this running and capture log at the time when the issue is happening.

**Comment by Swabeats** [comment]
Edit: so it’s the regular switch that doesn’t let the sonoff respond. In the app no mistakes. 
Ok. Will do it tonight.
Yeah, strange. Sonoff works in the app with no delay and faults AT ALL but the regular switch itself don’t works always. Just at this 3 places. I switched the regular switch also so I was like: ‘the fault is with the sonoff and not with my switch’. I changed one ‘bad’ one and issue was/is fixed. Thanks.

**Comment by maccoylton** [comment]
What gauge of wire are use using for the switch? When Initially tried, it didn’t work for me because the wire was to heavy a gauge. The switching side of the Sonoff is only 3v song so level

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Swabeats** [comment]
IDK how to do 'UDPlogger'. But I ran ping IPADRESS again and this was the outcome (photo)
Two times flags: 2 with two different Sonoff (?). 

Same gauge of wire as with all the other Sonoff  in the house. But 2 still have delay (same as usual). It works but sometimes I just have to do ON - OFF again and it's ok. After couple of times it's again delay and afterwards again ok. 
<img width="1385" alt="Screenshot 2020-01-29 at 15 05 24" src="https://user-images.githubusercontent.com/60329961/73363638-70f17500-42a9-11ea-9410-137f7632fbd5.png">
<img width="1392" alt="Screenshot 2020-01-29 at 15 06 36" src="https://user-images.githubusercontent.com/60329961/73363639-70f17500-42a9-11ea-9a86-333016792ddd.png">

**Comment by Swabeats** [comment]
Another one. Idk what flags mean tbh.
<img width="692" alt="Screenshot 2020-01-29 at 15 19 57" src="https://user-images.githubusercontent.com/60329961/73364479-f32e6900-42aa-11ea-82b9-089b7c63b270.png">

**Comment by Swabeats** [comment]
Gauge of wire: 1,5mm2

**Comment by maccoylton** [comment]
Are the traces above from when you actually seen the issue with the switch? If they are then my view is this is not a software issue .. but an issue with the hardware sonoff/wire or switch. 

Also see some discussion on the itead support  forum, with similar issue on stock firmware:- https://itead.freshdesk.com/support/discussions/topics/11000028147/page/3?url_locale=

**Comment by platinman** [comment]
Could you please share default password for homekit?

**Comment by maccoylton** [comment]
>Could you please share default password for homekit?

@platinman all 1s 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by platinman** [comment]
Hi maccoylton, thank you for your work. I need your help, my device cannot connect to HomeKit. I requested three files, the device switched to access point mode, after entering my WIFI password, an empty window appears and nothing else happens.
Can you explain what to do next?

**Comment by toshibochan** [comment]
@platinman Have to go home app and add the device.

**Comment by platinman** [comment]
The device is not detected.

**Comment by toshibochan** [comment]
Did you did this?
select your WiFi by clicking on it
enter your WiFi password
enter the GitHub directory - maccoylton/esp-homekit-sonoff-mini
enter filename - main.bin.
click the join button

**Comment by toshibochan** [comment]
After click the join button will install sonoff mini firmware. This will take 2 to 4 min after install you be able to see in home app

**Comment by platinman** [comment]
Thank you, I will go through all the steps carefully again.

**Comment by toshibochan** [comment]
https://github.com/maccoylton/esp-homekit-sonoff-mini/wiki

**Comment by maccoylton** [comment]
@platinman did you get this sorted ?

**Comment by platinman** [comment]
I read all your posts, thanks.
