### ISSUE TITLE
Can't keep connection to router

### ISSUE THREAD

**Issue by Siqy** [maccoylton/esp-homekit-sonoff-mini#8]
Dear Maccoylton,

More than a month ago, I have flashed 2 mini's with your firmware with succes.

I have orderd new ones, flashing goes according to plan. When the erase flash is finished the 3 .bin files are succesfully being flashed. Then I manually plug out the USB serial adapter and connect it back on the sonoff for the restart. WiFi spot of the mini is sending out, I can connect with my smartphone to it.
Then I do everything according to the wiki, password, github directory, file name main.bin is already in.
Next thing I log in my router, look at the wireless nodes and I see the sonoff mini can't hold connection up time more than about 5 seconds, then it resets (reconnects) again over and over. Tried 2 mini's, both having same problem.

Tried to disconnect it from the serial adapter and put 230V on the device, same problem. Looks like it can connect to the WiFi network but not to the github directory or something? Is it possible that it reboots all the time?
Had it left over more than an hour, still no firmware installed where the lights will burn on the sonoff and I can use the switching function by pressing the button or shorting the pins of the external switch option.

Thanks in advance.

**Comment by Siqy** [comment]
Update, I did everything according to wiki again for the OTA. Again connecting for few seconds to the router over and over.
Disconnected the mini, flashed the main.bin that I have downloaded on my PC straight on the mini with this command:
esptool.py --port COM8 --baud 230400 write_flash -fs 1MB -fm dout -ff 40m 0x2000 main.bin

After flashed, reconnected the mini. Started up like it should do, shows in Homekit now etc.

Think I have lost the auto updates by OTA I guess, but looks like somehow the mini's cant connect to the github repository. Tried other network, same problem.

**Comment by platinman** [comment]
Hi Siqy!!! How did you downloaded the  file main.bin

**Comment by platinman** [comment]
I have the same problem.

**Comment by platinman** [comment]
Siqy your advice helped me.

**Comment by maccoylton** [comment]
Microsoft made a change to GitHub recently that BROKE our OTA capability. See note here:- https://github.community/t5/GitHub-API-Development-and/GitHub-changed-the-capitalisation-of-the-HTTP-headers-and-OTA/td-p/48247

I will shortly update the wiki with instructions to address this with a new version of the boot loader and OTA designed to allow more options if this ever happens again

**Comment by Siqy** [comment]
Thnx for the fast reply. Good to know the problem. You are awesome.

**Comment by maccoylton** [comment]
For any device with an issue update it with the latest pre-release version of robot4lcm and LCM, to do this you need to follow the Wiki just as if it were a new devices.
