### ISSUE TITLE
Firmware .bin files

### ISSUE THREAD

**Issue by tasbarba** [maccoylton/esp-homekit-sonoff-mini#9]
Hi maccoylton!

Congrats for your great work! Could you help me?

I'm little bit newbie regarding building the firmware to flash de sonoff. I tried to install several SDK's but couldn't make the .bin file to flash the Sonoff mini.

Could you help me? Could you give me a hint on how to proceed, or to send me the firmware file so I just flash the device?

Thank you a lot.

Thiago.

**Comment by maccoylton** [comment]
Check out the wiki, it has instructions on downloading the bootloader and installing the firmware.

**Comment by toshibochan** [comment]
1-
download latest otaboot.bin from this link:
https://github.com/HomeACcessoryKid/life-cycle-manager/releases

download blank_config.bin and rboot.bin from this:
https://github.com/SuperHouse/esp-open-rtos/raw/master/bootloader/firmware_prebuilt/rboot.bin
https://github.com/SuperHouse/esp-open-rtos/raw/master/bootloader/firmware_prebuilt/blank_config.bin

2-
install the firmware to the device:
Im using /dev/ttyUSB0 in linux. change depends on what OS you using:
esptool -p /dev/ttyUSB0 --baud 115200 write_flash -fs 1MB -fm dout -ff 40m \ 0x0 rboot.bin 0x1000 blank_config.bin 0x2000 otaboot.bin

3-
When your device restarts, it will be operating as a Wifi access point, connect to the device with your iOS device, by selecting it in settings->wifi and select the one start with LCM- 
![IMG_3491](https://user-images.githubusercontent.com/15816913/78511715-cfc4e600-7753-11ea-8961-646a50ace296.png)
. You will then be promoted with a configuration web page:-

select your WiFi by clicking on it
enter your WiFi password
enter the GitHub directory - maccoylton/esp-homekit-sonoff-mini
enter filename - main.bin.
click the join button
the installation going to take a while wait till show up in the home app in the pairing process.
The device will now re-boot, connect to your Wifi network, download and flash the main.bin file 
from the latest release from the repository github.com/maccoylton/esp-homekit-sonoff-mini. 

4-
Once this is completed the device will reboot again and be ready to be paired like any standard HomeKit Accessory.

**Comment by tasbarba** [comment]
Thank you guys! After send you the message I found the wiki and also the main.bin file.

As I couldn't solder the pins in the mini, I tried the OTA firmware approach using the Sonoff_Devices_DIY_Tools from itead, on a Windows machine. I was able to flash the main.bin firmware using the itead tool, but I don't know if it was correct to proceed this way. It seems the Sonoff-mini is not working, maybe I bricked the device...

**Comment by toshibochan** [comment]
If you have a way to solder the pins you can erase and install new firmware

**Comment by tasbarba** [comment]
Ok, I'll try to solder the pins. But it is not possible to flash directly over wifi? Without soldering? That would be very helpful!

**Comment by maccoylton** [comment]
Flashing main.bin with sonoff tools will brick the device. 

Only way out is to solder. 

Alternative it create a flashing jig. I create  jigs by taking picture of the device next to a measuring tape, printing that picture out to scale and using that to bore holes for pogo pins to go through. The jig can then be held to the device long enough to flash the firmware. And one you have it you can do multiple devices.

**Comment by maccoylton** [comment]
The latest Wiki instructions include a link to a bootlader.bin file, which it **MAY** be possible to use to do the initial conversion OTA using sonoff diy tools. 

**NOTE, however I do not currently have a device to test this with, so try it AT YOUR OWN RISK**

**Comment by tasbarba** [comment]
> Flashing main.bin with sonoff tools will brick the device.
> 
> Only way out is to solder.
> 
> Alternative it create a flashing jig. I create jigs by taking picture of the device next to a measuring tape, printing that picture out to scale and using that to bore holes for pogo pins to go through. The jig can then be held to the device long enough to flash the firmware. And one you have it you can do multiple devices.

Good idea! Thank you!

**Comment by tasbarba** [comment]
> The latest Wiki instructions include a link to a bootlader.bin file, which it **MAY** be possible to use to do the initial conversion OTA using sonoff diy tools.
> 
> **NOTE, however I do not currently have a device to test this with, so try it AT YOUR OWN RISK**

I soldered the pins, but as I mentioned I think I bricked the device. You idea of the bootloader.bin is nice as well. Maybe I could try with another device.

Thank you for your attention!

**Comment by toshibochan** [comment]
@tasbarba you have to hold the button in sonoff-mini when you plug to the computer to erase or upload the firmware. After you hold and connect to the computer you can let go the button and you can upload.

**Comment by maccoylton** [comment]
@tasbarba  you need the jumper in place and to hold the button in as @toshibochan  suggested.  If you monitor the port as you power on you will see the boot mode, which tells you if you are in flashing mode or not.

**Comment by manoelmatos** [comment]
hello friends, the link to download the bootlader.bin file is not working
https://github.com/maccoylton/esp-homekit-sonoff-min/releases

![Sem título](https://user-images.githubusercontent.com/53665993/78949459-fa8ba300-7aa1-11ea-852a-da452fd02094.png)

**Comment by toshibochan** [comment]
Try this
https://github.com/maccoylton/esp-homekit-sonoff-mini/releases

**Comment by maccoylton** [comment]
Wiki fixed .. thanks

**Comment by tasbarba** [comment]
> @tasbarba you need the jumper in place and to hold the button in as @toshibochan suggested. If you monitor the port as you power on you will see the boot mode, which tells you if you are in flashing mode or not.

Thanks maccoylton. Unfortunately I couldn't solder the pins correctly and when I tried to remove it to solder again, I ended up screwing up the metal on the pin =(. I ordered another mini and will try to flash the bootloader.bin via OTA. If doesn't work I'll try to solder... but as you can see, I'm not skilled lol...

**Comment by maccoylton** [comment]
I'd recommend making a jig .. the way you do not need to solder

**Comment by tasbarba** [comment]
> The latest Wiki instructions include a link to a bootlader.bin file, which it **MAY** be possible to use to do the initial conversion OTA using sonoff diy tools.
> 
> **NOTE, however I do not currently have a device to test this with, so try it AT YOUR OWN RISK**

I tried to flash the bootloader.bin file via itead DYI mode tool, but it says that firmware must be dout.

**Comment by maccoylton** [comment]
If you stil have a divice to test with and I've just published a new bootloader file, which should be DOUT

**Comment by tasbarba** [comment]
Hi maccoylton, I flashed the bootloader.bin file to the mini via OTA, using the new DOUT file. But no wifi network unfortunatelly... =(
The device don't show up as a wifi access point...

**Comment by maccoylton** [comment]
>Hi maccoylton, I flashed the bootloader.bin file to the mini via OTA, using the new DOUT file. But no wifi network unfortunatelly... =( ...

@tasbarba ok so if you solder the pins or make a jig as I described before then it would be useful to get a dump of the flash off that device to try and figure out why it doesn’t work. I’m not at my computer right now I will post a command to do that a little later. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by maccoylton** [comment]
Command would be :- 

 esptool.py  -p **_/dev/cu.wchusbserial1a20_**  --baud 74880 read_flash 0x000000 524288 flash_512.bin

make sure to set the -p for your set.

**Comment by jihao** [comment]
I find this 3D printable jig.  https://www.thingiverse.com/thing:3817574 


![featured_preview_20190818_220852](https://user-images.githubusercontent.com/322532/80307244-57a18b80-87fa-11ea-995d-c0fcd7c463ec.jpg)

**Comment by maccoylton** [comment]
Nice if you have a 3d printer

**Comment by jihao** [comment]
Is it OK to just flash with main.bin?  if I don't need OTA update.
 
`esptool -p /dev/ttyUSB0 --baud 115200 write_flash -fs 1MB -fm dout -ff 40m \ 0x0 rboot.bin 0x1000 blank_config.bin 0x2000 ` **main.bin**

I am asking this because I tried this way, no WiFi AP showed up, so I might did it wrong.

**Comment by maccoylton** [comment]
No this is designed to work specifically with OTA
